### ISSUE TITLE
×「email」とハイフンありの1語とします

### ISSUE THREAD

**Issue by suchi** [nishinos/it-english-style-guide#1]
[word-lsit.md](https://github.com/nishinos/it-english-style-guide/blob/main/docs/word-list.md#email-e-mail)

> 「email」とハイフン**あり**の1語とします。「e〜」は、emailを除いてハイフンを付ける形とします。

文脈からも

> 「email」とハイフン**なし**の1語とします。「e〜」は、emailを除いてハイフンを付ける形とします。

の間違いかと思われます

**Comment by nishinos** [comment]
ありがとうございます！
さっそく修正しておきました。
